-- Alternative: Run these SQL commands in Supabase SQL Editor to manually create admin user
-- This bypasses the need for service_role key

-- First, create a user in auth.users (you'll need to get the UUID from Supabase Auth)
-- Then run this:

-- INSERT INTO auth.users (
--   instance_id,
--   id,
--   aud,
--   role,
--   email,
--   encrypted_password,
--   email_confirmed_at,
--   invited_at,
--   confirmation_token,
--   confirmation_sent_at,
--   recovery_token,
--   recovery_sent_at,
--   email_change_token_new,
--   email_change,
--   email_change_sent_at,
--   last_sign_in_at,
--   raw_app_meta_data,
--   raw_user_meta_data,
--   is_super_admin,
--   created_at,
--   updated_at,
--   phone,
--   phone_confirmed_at,
--   phone_change,
--   phone_change_token,
--   phone_change_sent_at,
--   email_change_token_current,
--   email_change_confirm_status,
--   banned_until,
--   reauthentication_token,
--   reauthentication_sent_at
-- ) VALUES (
--   '00000000-0000-0000-0000-000000000000',
--   'your-generated-uuid-here',
--   'authenticated',
--   'authenticated',
--   'admin@app.local',
--   crypt('admin12!', gen_salt('bf')),
--   NOW(),
--   NULL,
--   '',
--   NULL,
--   '',
--   NULL,
--   '',
--   '',
--   NULL,
--   NULL,
--   '{"provider": "email", "providers": ["email"]}',
--   '{"username": "admin"}',
--   FALSE,
--   NOW(),
--   NOW(),
--   NULL,
--   NULL,
--   '',
--   '',
--   NULL,
--   '',
--   0,
--   NULL,
--   NULL,
--   NULL
-- );

-- Then create the user profile:
-- INSERT INTO public.users (id, username, organization_id, role)
-- VALUES ('your-generated-uuid-here', 'admin', 'default-org', 'admin');
